// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Allin.Inventory.Infrastructure;
using Allin.Inventory.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Allin.Inventory.Infrastructure.Configurations
{
    public partial class InventoryItemConfiguration : IEntityTypeConfiguration<InventoryItem>
    {
        public void Configure(EntityTypeBuilder<InventoryItem> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Inventor__727E838B2FC59BA8");

            entity.ToTable("InventoryItems", "inventory");

            entity.Property(e => e.Code).HasMaxLength(50);
            entity.Property(e => e.Code2).HasMaxLength(50);
            entity.Property(e => e.Code3).HasMaxLength(50);
            entity.Property(e => e.Code4).HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.ItemTitle).HasMaxLength(100);
            entity.Property(e => e.ItemTypeId).HasComment("Assets(Machines,...), Consumable, Salable Product");
            entity.Property(e => e.Manufacturer).HasMaxLength(100);
            entity.Property(e => e.ModelNumber).HasMaxLength(50);
            entity.Property(e => e.ModifiedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Category).WithMany(p => p.InventoryItems)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Inventory__Categ__2B3F6F97");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InventoryItem> entity);
    }
}
