// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Allin.Inventory.Infrastructure;
using Allin.Inventory.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Allin.Inventory.Infrastructure.Configurations
{
    public partial class InventoryCategoryPropertyConfiguration : IEntityTypeConfiguration<InventoryCategoryProperty>
    {
        public void Configure(EntityTypeBuilder<InventoryCategoryProperty> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_ItemsProperty_Id");

            entity.ToTable("InventoryCategoryProperties", "inventory");

            entity.Property(e => e.Title).HasMaxLength(50);
            entity.Property(e => e.UniqueName).HasMaxLength(50);

            entity.HasOne(d => d.Category).WithMany(p => p.InventoryCategoryProperties)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_InventoryCategoryProperties_InventoryCategories");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InventoryCategoryProperty> entity);
    }
}
