// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Allin.Inventory.Infrastructure;
using Allin.Inventory.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Allin.Inventory.Infrastructure.Configurations
{
    public partial class InventoryCategoryAllowdMeasureConfiguration : IEntityTypeConfiguration<InventoryCategoryAllowdMeasure>
    {
        public void Configure(EntityTypeBuilder<InventoryCategoryAllowdMeasure> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_CommodityCategoryMeasures_Id");

            entity.ToTable("InventoryCategoryAllowdMeasures", "inventory");

            entity.HasIndex(e => new { e.CategoryId, e.MeasureId }, "IX_CommodityCategoryMeasures").IsUnique();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InventoryCategoryAllowdMeasure> entity);
    }
}
