// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Allin.Inventory.Infrastructure;
using Allin.Inventory.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Allin.Inventory.Infrastructure.Configurations
{
    public partial class InventoryItemAllowdMeasureConfiguration : IEntityTypeConfiguration<InventoryItemAllowdMeasure>
    {
        public void Configure(EntityTypeBuilder<InventoryItemAllowdMeasure> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_CommodityMeasures_Id");

            entity.ToTable("InventoryItemAllowdMeasures", "inventory");

            entity.HasIndex(e => new { e.ItemId, e.MeasureId }, "IX_CommodityMeasures").IsUnique();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InventoryItemAllowdMeasure> entity);
    }
}
