// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Allin.Inventory.Infrastructure;
using Allin.Inventory.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Allin.Inventory.Infrastructure.Configurations
{
    public partial class InventoryPropertyValueConfiguration : IEntityTypeConfiguration<InventoryPropertyValue>
    {
        public void Configure(EntityTypeBuilder<InventoryPropertyValue> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_CommodityPropertyValues");

            entity.ToTable("InventoryPropertyValues", "inventory");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InventoryPropertyValue> entity);
    }
}
