// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Allin.Inventory.Infrastructure;
using Allin.Inventory.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Allin.Inventory.Infrastructure.Configurations
{
    public partial class InventoryCategoryPropertyItemConfiguration : IEntityTypeConfiguration<InventoryCategoryPropertyItem>
    {
        public void Configure(EntityTypeBuilder<InventoryCategoryPropertyItem> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_CommodityCategoryPropertyItems");

            entity.ToTable("InventoryCategoryPropertyItems", "inventory");

            entity.Property(e => e.Code).HasMaxLength(50);

            entity.HasOne(d => d.CategoryProperty).WithMany(p => p.InventoryCategoryPropertyItems)
                .HasForeignKey(d => d.CategoryPropertyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_InventoryCategoryPropertyItems_InventoryCategoryProperties");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InventoryCategoryPropertyItem> entity);
    }
}
