// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Allin.Inventory.Infrastructure;
using Allin.Inventory.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Allin.Inventory.Infrastructure.Configurations
{
    public partial class InventoryItemTypeConfiguration : IEntityTypeConfiguration<InventoryItemType>
    {
        public void Configure(EntityTypeBuilder<InventoryItemType> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Inventor__F51540FB0C725706");

            entity.ToTable("InventoryItemTypes", "inventory");

            entity.HasIndex(e => e.ItemTypeName, "UQ__Inventor__1FA416B00E8A2ECE").IsUnique();

            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.IsOperational).HasDefaultValue(false);
            entity.Property(e => e.ItemTypeName).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InventoryItemType> entity);
    }
}
