// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Allin.Inventory.Infrastructure.Persistence.Configurations
{
    public partial class BaseValueItemConfiguration : InventoryTypeConfiguration<BaseValueItem>
    {
        public void Configure(EntityTypeBuilder<BaseValueItem> builder)
        {
            builder.ToTable("BaseValueItems", "Admin");

            base.Configure(builder);
        }
    }
}
