// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Allin.Inventory.Infrastructure.Persistence.Configurations
{
    public partial class BaseValueItemConfiguration : IEntityTypeConfiguration<BaseValueItem>
    {
        public void Configure(EntityTypeBuilder<BaseValueItem> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_BaseValues_1");

            entity.ToTable("BaseValueItems", "admin");

            entity.Property(e => e.Description).HasMaxLength(300);
            entity.Property(e => e.Title).HasMaxLength(150);

            entity.HasOne(d => d.BaseValue).WithMany(p => p.BaseValueItems)
                .HasForeignKey(d => d.BaseValueId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BaseValues_BaseValueTypes");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BaseValueItem> entity);
    }
}
