// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Allin.Inventory.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Allin.Inventory.Infrastructure.Persistence.Entities.Configurations
{
    public partial class InventoryCategoryAllowdMeasureConfiguration : InventoryTypeConfiguration<InventoryCategoryAllowdMeasure>
    {
        public void Configure(EntityTypeBuilder<InventoryCategoryAllowdMeasure> builder)
        {
            builder.ToTable("BaseValueItems", "Admin");

            base.Configure(builder);
        }

    }
}
