// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Allin.Inventory.Infrastructure.Persistence.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace Allin.Inventory.Infrastructure.Persistence.Configurations
{
    public partial class InventoryCategoryPropertyItemConfiguration : InventoryTypeConfiguration<InventoryCategoryPropertyItem>
    {
        public void Configure(EntityTypeBuilder<InventoryCategoryPropertyItem> builder)
        {
            builder.ToTable("InventoryCategoryPropertyItems", "Inventory");

            base.Configure(builder);
        }
    }
}
